dist: bionic

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  include:
    - php: '5.5.9'
      env: DEPENDENCIES=low
      dist: trusty
    - php: '5.6'
      dist: xenial
    - php: '7.0'
      dist: xenial
    - php: '7.4'
      env: DEPENDENCIES=dev

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then composer config platform.php 7.4.99; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; else composer install; fi;

script: ./vendor/bin/phpunit
