dist: bionic

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

matrix:
  include:
    - php: '5.5.9'
      env: DEPENDENCIES=low
      dist: trusty
    - php: '5.6'
      dist: xenial
    - php: '7.0'
      dist: xenial
    - php: '7.4'
      env: DEPENDENCIES=dev

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; else composer install; fi;
  - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit
